### ISSUE TITLE
Implementing umbrella (void) parent language with well-defined child language(s)

### ISSUE THREAD

**Issue by atreyasha** [github/linguist#4860]
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

I would ultimately like to submit a PR for recognition of a new language called "Answer Set Programming". However, before doing so, I would like to clarify a few things through this GitHub issue. I have ommitted some parts of the template since I only intend to ask a question. I hope that is alright.

1. As mentioned, we want to create a new parent language group called "Answer Set Programming" (https://en.wikipedia.org/wiki/Answer_set_programming), which is similar to Prolog and is now essentially an umbrella term for various frameworks, such as `clingo` and `gringo`. An example of `clingo` code can be found [here](https://github.com/atreyasha/clingoSolvers/blob/master/elevator.lp).

2. The issue here is that we don't really have generic file extensions or an agreed upon syntax for "Answer Set Programming". Instead, each framework branches off in its own (albeit similar) syntax and file extensions.

3. In that case, I was wondering if it would be possible for us to submit a PR for the creation of a parent language called "Answer Set Programming". However, we intend to leave out the syntax and file extensions for this parent language. Instead, we will add child language(s) (with group annotations in `languages.yml`) which will have their own syntax and file extensions and these will count towards the parent language in language statistics.

4. I had skimmed the GitHub issues and `languages.yml` and could not find any other similar implementations, so I guess this request would be rather obscure. But nonetheless I thought it would be good to ask beforehand.

Thank you for your time.

**Comment by pchaigno** [comment]
>     3\. In that case, I was wondering if it would be possible for us to submit a PR for the creation of a parent language called "Answer Set Programming". However, we intend to leave out the syntax and file extensions for this parent language. Instead, we will add child language(s) (with group annotations in `languages.yml`) which will have their own syntax and file extensions and these will count towards the parent language in language statistics.

I'm :+1: for that as long as each extension meets our requirement of *hundreds of repositories*.

Please note that all languages will be displayed in statistics as "Answer Set Programming". Also, defining a grammar for a new language isn't a requirement, but in that case it might be easier to list extensions for the language without grammar directly under "Answer Set Programming" as that would essentially achieve the same effect.

**Comment by atreyasha** [comment]
@pchaigno thank you for that.

Before submitting a pull request, I'd like to get your opinion whether [this](https://github.com/search?q=extension%3Alp+NOT+nothack+clingo&type=Repositories) already counts as *hundreds of repositories*?

From my POV it seems technically so, but would be good to know beforehand whether we would have a reasonable chance of having the PR approved given this statistic.

**Comment by pchaigno** [comment]
Using [Harvester](https://github.com/Alhadis/Harvester), I downloaded the 1034 [files matching that search query](https://github.com/search?q=extension%3Alp+clingo&type=Code) and counted 161 repositories by 132 users. So no, that would not match our requirement for in-the-wild usage just yet.

Is there another search query that would be more accurate? Do you expect that number to grow significantly in the next few months?

**Comment by atreyasha** [comment]
Oh I see. I tried searching on my browser with the modified query:

```
extension:lp "answer set programming" OR "clingo"
```

Now, the number of repositories is 306. Would this be feasible? As this is a logic-programming language taught in University and used in the industry, I think it would be realistic to expect the numbers to rise quickly.

**Comment by atreyasha** [comment]
I had tried to run this query via `Harvester` but came across an error. This [page](https://github.com/search?q=extension%3Alp+"answer+set+programming"+OR+"clingo") is the search result on the GitHub UI.

**Comment by atreyasha** [comment]
@Alhadis my bad, I use a light-weight browser by default and had to change to firefox to get the console working. Initially I was not logged in to GitHub on firefox while trying the `js` code for `Harvest`. It is working now after logging in.

Will share the results once the search query finishes.

**Comment by Alhadis** [comment]
What browser, exactly? It should work with any browser with a modern JavaScript engine.

**Comment by atreyasha** [comment]
Qutebrowser. I am new to it so maybe that's just my incompetence.

The search query looks quite similar to before:

```
Files with .lp extension: 1194
Unique repos: 169
Unique users: 139
```

WDYT?

**Comment by atreyasha** [comment]
Update: Managed to get more accurate numbers with a modified search query

```
Query: extension:lp "answer set" OR "clingo" OR "gringo" OR "clasp"
Files with .lp extension: 2042
Unique repos: 214
Unique users: 176
```

**Comment by atreyasha** [comment]
Update: Managed to get more accurate numbers with a modified search query

```
Query: extension:lp "answer set" OR "clingo" OR "gringo" OR "clasp"
Files with .lp extension: 2042
Unique repos: 214
Unique users: 176
```

@pchaigno would these numbers be good enough for us to justify an (eventual) PR?

**Comment by pchaigno** [comment]
> @pchaigno would these numbers be good enough for us to justify an (eventual) PR?

Yes, that might be enough, but I'm worried about conflicting languages. Files matched by [this query](https://github.com/search?p=1&q=extension%3Alp+NOT+%22answer+set%22+NOT+clingo+NOT+gringo+NOT+clasp&type=Code) are, for the most part, not Answer Set Programming files, right? If we add support for a file extension, we need to support all languages that uses it and are widespread enough. Otherwise, Linguist will recognize them all as Answer Set Programming :-/

**Comment by atreyasha** [comment]
Thank you for the feedback. Yes, unfortunately those files from the above search query are not all part of "Answer Set Programming". Based on a quick look, the first few seem to have a HTML syntax, the others I am not too sure.

For this, I have a couple of perspectives.

1. Based on [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml), there is no other language which has reserved the `.lp` extension. In that sense, I don't see anything wrong if we try to use it first. If someone using the `.lp` extension in the future has a higher repository count than ours, they could submit an issue/PR and we could then try to reach a compromise.

2. I think for rare languages and file extensions, there would always be a chance of wrong reporting. But in those cases above, affected users could use manual overrides to prevent that.

**Comment by Alhadis** [comment]
@atreyasha It may interest you to know that many of the entries in `languages.yml` were actually discovered while researching potential conflicts like this one. It isn't uncommon for 2 or even 3 unrelated languages to wind up being submitted together, simply because nobody had researched the given extension thoroughly enough.

**Comment by atreyasha** [comment]
@Alhadis thank you for that. But specific to this issue, what other steps should I/we be taking to reduce the changes of conflict for the `.lp` extension?

**Comment by Alhadis** [comment]
It actually is specific to this issue. If there are conflicts with languages that are widespread enough to qualify for registration as well, then they need to be added so Linguist can tell them apart. Linguist can only identify languages it's familiar with; if there's only one language associated with an extension, it blindly assumes that file to be the language in question.

**Comment by atreyasha** [comment]
>But specific to this issue, what other steps should I/we be taking to reduce the chances of conflict for the .lp extension?

What steps should I/we take? I understand there are problems, that is clear.

**Comment by Alhadis** [comment]
[Adding a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) is explained in detail in [the contributing guide](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#contributing).

**Comment by atreyasha** [comment]
>Adding a language is explained in detail in the contributing guide.

@Alhadis I already know this. This is not my point.

I opened this issue to iron out all the fine-details (specific to my case) that I need to know before opening a PR.

>It actually is specific to this issue. If there are conflicts with languages that are widespread enough to qualify for registration as well, then they need to be added so Linguist can tell them apart. Linguist can only identify languages it's familiar with; if there's only one language associated with an extension, it blindly assumes that file to be the language in question.

My point is what can I do to address this concern of yours? Should I also make a PR for all other "languages" using the `.lp` extension? I don't even know if others using the `.lp` extension are implementing a language, as we are. Please clarify, I am confused.

**Comment by Alhadis** [comment]
> I don't even know if others using the `.lp` extension are implementing a language, as we are. Please clarify, I am confused.

That's the hard part. Using [Harvester](https://github.com/Alhadis/Harvester), collect as many URLs as possible, then download them *en masse*, and go through them locally. This process can be arduous and time-consuming, which is why I'm usually the one who ends up putting in time to research the extension's usage. Unfortunately, time isn't something I have at the moment, hence why I'm explaining instead of doing it. 😜

If it's 50-50 between your language and one you don't recognise, that's a good indication that it's worth looking into.

**Comment by atreyasha** [comment]
> That's the hard part. Using [Harvester](https://github.com/Alhadis/Harvester), collect as many URLs as possible, then download them _en masse_, and go through them locally. This process can be arduous and time-consuming, which is why I'm usually the one who ends up putting in time to research the extension's usage. Unfortunately, time isn't something I have at the moment, hence why I'm explaining instead of doing it. 

I understand now. I was running `Harvester` for the last 20 mins on the other `.lp` implomentations during this conversation, because I thought it might come into use.

> If tallying the results gives ~50-50 between your language and one you don't recognise, that's a good indication that it's worth looking into.

The results are unfortunately ~50-50. Grey area once again; the other "languages" are distributed into sub-groups. Some files have a HTML-like syntax, some are purely text files and others are of some mathematical optimization language. I doubt any of these sub-groups have more than 200 unique repos.

In any case, I assume you would need such an investigation into `.lp` usage of "Answer Set Programming" vs. `.lp` usage in other languages. So I guess this is something we should probably address in a future PR. But good to know what all we would need to address.
